<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SurveyDB" Member="SurveyDBs">
    <Type Name="SurveyDB">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullNames" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FOOD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MovieInterest" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RadioInterest" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EatOutInterest" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TvInterest" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>