#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApp_API
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSurveyDB(SurveyDB instance);
    partial void UpdateSurveyDB(SurveyDB instance);
    partial void DeleteSurveyDB(SurveyDB instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SurveyDB> SurveyDBs
		{
			get
			{
				return this.GetTable<SurveyDB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SurveyDB")]
	public partial class SurveyDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FullNames;
		
		private string _Email;
		
		private System.Nullable<int> _Age;
		
		private string _ContactNumber;
		
		private string _FOOD;
		
		private System.Nullable<int> _MovieInterest;
		
		private System.Nullable<int> _RadioInterest;
		
		private System.Nullable<int> _EatOutInterest;
		
		private System.Nullable<int> _TvInterest;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFullNamesChanging(string value);
    partial void OnFullNamesChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnFOODChanging(string value);
    partial void OnFOODChanged();
    partial void OnMovieInterestChanging(System.Nullable<int> value);
    partial void OnMovieInterestChanged();
    partial void OnRadioInterestChanging(System.Nullable<int> value);
    partial void OnRadioInterestChanged();
    partial void OnEatOutInterestChanging(System.Nullable<int> value);
    partial void OnEatOutInterestChanged();
    partial void OnTvInterestChanging(System.Nullable<int> value);
    partial void OnTvInterestChanged();
    #endregion
		
		public SurveyDB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNames", DbType="NVarChar(500)")]
		public string FullNames
		{
			get
			{
				return this._FullNames;
			}
			set
			{
				if ((this._FullNames != value))
				{
					this.OnFullNamesChanging(value);
					this.SendPropertyChanging();
					this._FullNames = value;
					this.SendPropertyChanged("FullNames");
					this.OnFullNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="VarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOOD", DbType="VarChar(20)")]
		public string FOOD
		{
			get
			{
				return this._FOOD;
			}
			set
			{
				if ((this._FOOD != value))
				{
					this.OnFOODChanging(value);
					this.SendPropertyChanging();
					this._FOOD = value;
					this.SendPropertyChanged("FOOD");
					this.OnFOODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieInterest", DbType="Int")]
		public System.Nullable<int> MovieInterest
		{
			get
			{
				return this._MovieInterest;
			}
			set
			{
				if ((this._MovieInterest != value))
				{
					this.OnMovieInterestChanging(value);
					this.SendPropertyChanging();
					this._MovieInterest = value;
					this.SendPropertyChanged("MovieInterest");
					this.OnMovieInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RadioInterest", DbType="Int")]
		public System.Nullable<int> RadioInterest
		{
			get
			{
				return this._RadioInterest;
			}
			set
			{
				if ((this._RadioInterest != value))
				{
					this.OnRadioInterestChanging(value);
					this.SendPropertyChanging();
					this._RadioInterest = value;
					this.SendPropertyChanged("RadioInterest");
					this.OnRadioInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EatOutInterest", DbType="Int")]
		public System.Nullable<int> EatOutInterest
		{
			get
			{
				return this._EatOutInterest;
			}
			set
			{
				if ((this._EatOutInterest != value))
				{
					this.OnEatOutInterestChanging(value);
					this.SendPropertyChanging();
					this._EatOutInterest = value;
					this.SendPropertyChanged("EatOutInterest");
					this.OnEatOutInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TvInterest", DbType="Int")]
		public System.Nullable<int> TvInterest
		{
			get
			{
				return this._TvInterest;
			}
			set
			{
				if ((this._TvInterest != value))
				{
					this.OnTvInterestChanging(value);
					this.SendPropertyChanging();
					this._TvInterest = value;
					this.SendPropertyChanged("TvInterest");
					this.OnTvInterestChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
